version: "3"
services:

  vote:
    image: dockersamples/vote
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - frontend

  worker:
    image: dockersamples/worker
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend

  result:
    image: dockersamples/result
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db

networks:
  frontend:
  backend:
